#!/bin/sh

ADDONNAME=ccu-historian
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

stop() {
    echo -n "Stopping CCU-Historian... "
    logger -t homematic -p user.info "stopping ccu-historian"
    start-stop-daemon -K -q -p /var/run/ccu-historian.pid
    echo "OK"
}

start() {
    echo -n "Starting CCU-Historian... "
    logger -t homematic -p user.info "starting ccu-historian"
    if [ -x "/opt/jre/bin/java" ]; then
      # we are on RaspberryMatic
      JAVA_BIN=/opt/jre/bin/java
      MAXHEAP=768m
    else
      # we run on CCU2
      JAVA_BIN=/opt/ejre1.7.0_10/bin/java
      MAXHEAP=32m
    fi
    start-stop-daemon -S -q -b -m -p /var/run/ccu-historian.pid --exec ${JAVA_BIN} -- -Xmx${MAXHEAP} -jar ${ADDON_DIR}/ccu-historian/ccu-historian.jar -config ${ADDON_DIR}/ccu-historian.config -loglevel off
    echo "OK"
}

info() {
    echo "Info: <b>CCU-Historian Addon</b><br>"
    echo "Info: <a href="https://github.com/jens-maus/hm-ccu-historian" target="_blank">https://github.com/jens-maus/hm-ccu-historian</a>"
    echo "Name: CCU-Historian"
    echo "Version: $(cat ${ADDON_DIR}/VERSION)"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/ccu-historian/config.cgi"
    echo "Update: /addons/ccu-historian/update-check.cgi"
}

uninstall() {
    stop
    ${ADON_DIR}/update_addon ccu-historian
    rm -rf ${ADDON_DIR}
    rm ${RCD_DIR}/ccu-historian
    rm -rf ${WWW_DIR}
    logger -t homematic -p user.info "uninstalled ccu-historian"
}

case "$1" in
  ""|start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 2
	start
	;;
  uninstall)
    uninstall
    ;;
  info)
    info
    ;;
  *)
    echo "Usage: ccu-historian {start|stop|restart|info|uninstall}" >&2
    exit 1
    ;;
esac

exit $?
