#!/bin/sh

stop() {
    echo -n "Stopping CCU Historian... "
    logger -t homematic -p user.info "stopping ccu-historian"
    start-stop-daemon -K -q -p /var/run/ccu-historian.pid
    echo "OK"
}

start() {
    echo -n "Starting CCU Historian... "
    logger -t homematic -p user.info "starting ccu-historian"
    if [ -x "/opt/jre/bin/java" ]; then
      JAVA_BIN=/opt/jre/bin/java
    else
      JAVA_BIN=/opt/ejre1.7.0_10/bin/java
    fi
    start-stop-daemon -S -q -b -m -p /var/run/ccu-historian.pid --exec ${JAVA_BIN} -- -jar /usr/local/addons/ccu-historian/ccu-historian.jar -config /usr/local/addons/ccu-historian/ccu-historian.config -loglevel off
    echo "OK"
}

info() {
    VER=`cat /usr/local/addons/ccu-historian/VERSION`
    echo "Info: <b>CCU Historian Addon</b><br>"
    echo "Info: <a href="https://github.com/jens-maus/ccu-historian" target="_blank">https://github.com/jens-maus/ccu-historian</a>"
    echo "Name: CCU Historian"
    echo "Version: $VER"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/ccu-historian"
    echo "Update: /addons/ccu-historian/update-check.cgi"
}

uninstall() {
    stop
    /usr/local/addons/ccu-historian/update_addon ccu-historian
    rm -r /usr/local/addons/ccu-historian
    rm /usr/local/etc/config/rc.d/ccu-historian
    logger -t homematic -p user.info "uninstalled ccu-historian"
}

case "$1" in
  ""|start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 2
	start
	;;
  uninstall)
    uninstall
    ;;
  info)
    info
    ;;
  *)
    echo "Usage: ccu-historian {start|stop|restart|info|uninstall}" >&2
    exit 1
    ;;
esac

exit $?
