#!/bin/sh

if [ "$pkgwizard_confirm" = "false" ]; then
	case $SYNOPKG_DSM_LANGUAGE in
		ger)
			printf "Bitte die Warnung bestätigen!" > $SYNOPKG_TEMP_LOGFILE
		;;
		
		*)
			printf "Please confirm the warning!" > $SYNOPKG_TEMP_LOGFILE
		;;
	esac
	exit 1
fi

# When upgrading, we need to backup the config file and database first
/bin/cp -fpR "$SYNOPKG_PKGDEST/data/" $SYNOPKG_TEMP_UPGRADE_FOLDER
/bin/cp -f "$SYNOPKG_PKGDEST/ccu-historian.config" $SYNOPKG_TEMP_UPGRADE_FOLDER

exit 0
