#!/bin/sh
# Executes groovy scripts.

# check which java version to use
if [ -x "/opt/java/bin/java" ]; then
  # we are on CCU3/RaspberryMatic
  JAVA_BIN=/opt/java/bin/java
elif which java > /dev/null; then
  # java is on the search path 
  JAVA_BIN=java
else
  >&2 echo "ERROR: Java binary not found"
  exit 1
fi

# get dir of shell script
DIR=`dirname "$0"`

# start java with GroovyMain
${JAVA_BIN} -cp $DIR/ccu-historian.jar:$DIR/lib/*.jar groovy.ui.GroovyMain "$@"
