#!/bin/sh
# Executes groovy scripts.

# check which java version to use
if [ -x "/opt/java/bin/java" ]; then
  # we are on CCU3/RaspberryMatic
  JAVA_BIN=/opt/java/bin/java
elif which java > /dev/null; then
  # java is on the search path 
  JAVA_BIN=java
else
  >&2 echo "ERROR: Java binary not found"
  exit 1
fi

# start java with GroovyMain
${JAVA_BIN} -cp ccu-historian.jar:lib\*.jar groovy.ui.GroovyMain "$@"
