#!/bin/sh
# Executes groovy scripts. The H2 Database driver is included.

# check which java version to use
if [ -x "/opt/java/bin/java" ]; then
  # we are on RaspberryMatic beta3+
  JAVA_BIN=/opt/java/bin/java
elif [ -x "/opt/jre/bin/java" ]; then
  # we are on RaspberryMatic beta1-2
  JAVA_BIN=/opt/jre/bin/java
elif [ -x "/opt/jre-1.8.0_121-compact3/bin/java" ]; then
  # we run on CCU2/YAHM/LXCCU
  JAVA_BIN=/opt/jre-1.8.0_121-compact3/bin/java
elif which java > /dev/null; then
  # it is on the search path 
  JAVA_BIN=java
else
  >&2 echo "ERROR: Java binary not found"
  exit 1
fi

# start java with GroovyMain
${JAVA_BIN} -cp lib/groovy-all-2.4.13.jar:lib/commons-cli-1.2.jar:lib/h2-1.4.196.jar groovy.ui.GroovyMain "$@"
