var ChhLanguage = {
  'default': {
    'interface': {
      'search': 'Suche',
      'today': 'Heute',
      'clear': 'Zurücksetzen',
      'close': 'Schließen',
      'favorites': 'Favoriten',
      'openLink': 'Link erzeugen',
      pageTitle: 'CCU-historian: HighChart',
    },
    'historian': {
      //Datenpunkte
      'settings': 'Einstellungen',
      'axissetting': 'Achsen-Einstellung für Y-Axis',
      'interfaceId': 'Schnittstelle',
      'address': 'Seriennummer:Kanal',
      'identifier': 'Parameter',
      'preprocType': 'preprocType', //?
      'preprocParam': 'preprocParam', //?
      'displayName': 'Kanalname',
      'room': 'Raum',
      'function': 'Gewerk',
      'comment': 'Kommentar',
      'paramSet': 'Parameter Set', // ?
      'tabOrder': 'Tab Reihenfolge', // ?
      'maximum': 'Maximum',
      'unit': 'Einheit',
      'minimum': 'Minimum',
      'control': 'Typ', //?
      'operations': 'Operations', //??
      'flags': 'Flags', //?
      'type': 'Datentyp',
      'defaultValue': 'Standard Wert',
      'idx': 'Historian Id',

      // Std. Gewerke
      '${funcHeating}': 'Heizung',
      '${funcButton}': 'Schalter',
      '${funcLight}': 'Licht',
      '${funcEnergy}': 'Energiemanagement',
      '${funcWeather}': 'Wetter',

      //Std. Räume
      '${roomBedroom}': 'Schlafzimmer',
      '${roomOffice}': 'Büro',
      '${roomKitchen}': 'Küche',
      '${roomChildrensRoom1}': 'Kinderzimmer 1',
      '${roomGarden}': 'Garten',
      '${funcSecurity}': 'Sicherheit',

      // Select Option Filter default
      roomALL: 'alle Räume',
      sysvarALL: 'Systemvariablen',
      functionALL: 'alle Gewerke',
      favoritTxt: 'Favoriten',
      favoritNEW: 'hinzufügen',
      favoritTitle: 'Favorit wählen / anlegen',
      favoritName: 'Neuer Favoriten Name',

      // Button and Screen text
      buttonDay: 'Tag',
      buttonWeek: 'Woche',
      buttonMonth: 'Monat',
      buttonYear: 'Jahr',
      buttonALL: 'Alles',
      buttonRefresh: 'Refresh',
      buttonLink: 'Link erzeugen',
      labelValues: 'Werte',
      filterPlaceHolder: 'Suchen ...',
      fontsize: 'Font-Grösse',
      aggrtxt0: 'keine Aggregation',
      aggrtxt1: 'Dyna. Aggregation',
      aggrtxt2: 'Delta Aggregation',
      aggrtxt3: 'Min/Max Aggregation',
      aggrtxt4: 'Sum Aggregation',
      aggrtxt5: 'Time_On Aggregation',
      aggrtxt6: 'gerundet auf Min.',
      aggrtxt7: 'Delta+ Aggregation',
      aggrmonth: 'Monat',
      aggrweek: 'Woche',
      aggrday: 'Tag',
      aggrhour: 'Stunde',
      aggrminute: 'Minute',
      aggrsecond: 'Sekunde',
      aggrmonth2: 'Monate',
      aggrweek2: 'Wochen',
      aggrday2: 'Tage',
      aggrhour2: 'Stunden',
      aggrminute2: 'Minuten',
      aggrsecond2: 'Sekunden',
      atimetxt0: 'Dyna. Zeitraum',
      atimetxt1: 'Dyna. ab 15min.',
      atimetxt2: 'keine/Stunde/Tag',
      atimetxt3: 'fix auf Stunde',
      atimetxt4: 'fix auf Tag',
      atimetxt5: 'fix auf Woche',
      atimetxt6: 'fix auf Monat',
      atimetxt7: 'fix auf Quartal',
      atimetxt8: 'fix auf Jahr',
      atimetxt9: 'fix auf 3 Stunden',
      atimetxt10: 'fix auf 6 Stunden',
      atimetxt11: 'fix auf 8 Stunden',
      atimetxt12: 'fix auf 12 Stunden',
      yaxis0: 'Standard Y-Achse',
      yaxis1: 'Raum Temperatur 10-30°C',
      yaxis2: 'Außen Temperatur -20-50°C',
      yaxis3: 'Heizung Temperatur 20-90°C',
      yaxis4: 'Prozent 0-100%',
      yaxis5: 'Status 0-1',
      yaxis6: 'Luftfeuchtigkeit 20%-100%',
      yaxis7: 'Luftdruck 900-1000',
      yaxis8: 'Helligkeit 0-???',
      yaxis9: 'CO2 300-3000',
      yaxis10: 'Luftfeuchtigkeit g/kg',
      yaxis11: 'Linear',
      yaxis12: 'Logarithmic',
      yaxis13: 'Linear',
      yaxis14: 'Linear',
      yaxis15: 'Linear',
      yaxis16: 'Linear',
      yaxis17: 'Linear',
      yaxis18: 'Linear',
      yaxis19: 'Linear',
      yaxisText0: null,
      yaxisText1: 'Temperatur',
      yaxisText2: 'Außen Temperatur',
      yaxisText3: 'Heizung Temperatur',
      yaxisText4: 'Prozent %',
      yaxisText5: 'Status',
      yaxisText6: 'Luftfeuchtigkeit',
      yaxisText7: 'Luftdruck',
      yaxisText8: 'Helligkeit',
      yaxisText9: 'CO2',
      yaxisText10: 'Luftfeuchtigkeit g/kg',
      yaxisText11: null,
      yaxisText12: null,
      yaxisText13: null,
      yaxisText14: null,
      yaxisText15: null,
      yaxisText16: null,
      yaxisText17: null,
      yaxisText18: null,
      yaxisText19: null,
      yaxistype0: 'linear',
      yaxistype1: 'logarithmic',
      yaxispos0: 'links',
      yaxispos1: 'rechts',
      yaxislimit0: 'dynamic',
      yaxislimit1: 'soft',
      yaxislimit2: 'hard',
      linetype0: 'SP-Line',
      linetype1: 'Line',
      linetype2: 'Line step left',
      linetype3: 'Line step center',
      linetype4: 'Line step right',
      linetype5: 'Scatter',
      linetype6: 'SP-Area',
      linetype7: 'Area',
      linetype8: 'Area step left',
      linetype9: 'Area step center',
      linetype10: 'Area step right',
      linetype11: 'column',
      linewidth0: 'Linenstärke 0',
      linewidth1: 'Linenstärke 1',
      linewidth2: 'Linenstärke 2',
      linewidth3: 'Linenstärke 3',
      linewidth4: 'Linenstärke 4',
      linewidth5: 'Linenstärke 5',
      linewidth6: 'Linenstärke 6',
      linewidth7: 'Linenstärke 7',
      linewidth8: 'Linenstärke 8',
      linewidth9: 'Linenstärke 9',
      linewidth10: 'Linenstärke 10',
      comptype0: 'kein Vergleich',
      comptype1: 'Vergleich -1 Tag',
      comptype2: 'Vergleich -2 Tage',
      comptype3: 'Vergleich -3 Tage',
      comptype4: 'Vergleich -4 Tage',
      comptype5: 'Vergleich -1 Woche',
      comptype6: 'Vergleich -2 Wochen',
      comptype7: 'Vergleich -3 Wochen',
      comptype8: 'Vergleich -4 Wochen',
      comptype9: 'Vergleich -1 Monat',
      comptype10: 'Vergleich -2 Monate',
      comptype11: 'Vergleich -3 Monate',
      comptype12: 'Vergleich -4 Monate',
      comptype13: 'Vergleich -1 Jahr',
      comptypeC0: '',
      comptypeC1: '-1T',
      comptypeC2: '-2T',
      comptypeC3: '-3T',
      comptypeC4: '-4T',
      comptypeC5: '-1W',
      comptypeC6: '-2W',
      comptypeC7: '-3W',
      comptypeC8: '-4W',
      comptypeC9: '-1M',
      comptypeC10: '-2M',
      comptypeC11: '-3M',
      comptypeC12: '-4M',
      comptypeC13: '-1J',
      Stacking0: 'kein Stacking',
      Stacking1: 'Stacking Gruppe 1',
      Stacking2: 'Stacking Gruppe 2',
      Stacking3: 'Stacking Gruppe 3',
      Stacking4: 'Stacking Gruppe 4',
      Stacking5: 'Stacking Gruppe 5',
      datapoint0: 'beide nicht',
      datapoint1: 'kein Versteckten',
      datapoint2: 'kein Inaktiven',
      datapoint3: 'alle Datenpunkte',
      legendtxt0: 'ausblenden',
      legendtxt1: 'links',
      legendtxt2: 'rechts',
      legendtxt3: 'inline oben',
      legendtxt4: 'inline unten',
      legendtxt5: 'oben',
      legendtxt6: 'unten',
      navitxt0: 'Navigator+Scrollbar',
      navitxt1: 'Navigator',
      navitxt2: 'Scrollbar',
      navitxt3: 'nur Menü-Sysmbol',
      navitxt4: 'alles ausblenden',
      labeltxt0: 'ausblenden',
      labeltxt1: 'bei letzten Name einblenden',
      labeltxt2: 'Werte oberhalb einblenden',
      layouttxt0: 'ohne',
      layouttxt1: 'Tag gelb/Nacht grau',
      layouttxt2: 'Line Tag/Nacht',
      layouttxt3: 'Line um 00:00',
      gridtxt0: 'ohne',
      gridtxt1: 'Vertikale Linien',
      gridtxt2: 'Horizontale Linien',
      gridtxt3: 'Vert+Horz. Linien',
      gridtxt4: 'Vertikale Linien+',
      gridtxt5: 'Horizontale Linien+',
      gridtxt6: 'Vert+Horz. Linien+',
      contenttxt0: 'alles ausblenden',
      contenttxt1: 'Filter und Menü',
      contenttxt2: 'nur Filter Felder',
      contenttxt3: 'nur Historian-Menü',
      themenone: 'Standard',
      range30M: '30M',
      rangeH: 'H',
      range6H: '6H',
      rangeD: 'D',
      rangeW: 'W',
      rangeM: 'M',
      rangeY: 'Y',
      rangeALL: 'All',
      rangeTitle30M: '30 Minuten',
      rangeTitleH: '1 Stunde',
      rangeTitle6H: '6 Stunden',
      rangeTitleD: '1 Tag',
      rangeTitleW: '1 Woche',
      rangeTitleM: '1 Monat',
      rangeTitleY: '1 Jahr',
      rangeTitleALL: 'Alles',
      limitactive: 'alle DP anzeigen',
      limitdeactive: 'nur aktive DP',
      autorefreshText: 'Refresh in',

    },
    'highcharts': {
      decimalPoint: ',',
      thousandsSep: '.',
      loading: 'Daten werden geladen...',
      months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
      weekdays: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
      shortMonths: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
      downloadPNG: 'Download PNG-Bild',
      downloadJPEG: 'Download JPEG-Bild',
      downloadPDF: 'Download PDF-Dokument',
      downloadSVG: 'Download SVG-Bild',
      downloadCSV: 'Download CSV-Datei',
      downloadXLS: 'Download XLS-Datei',
      resetZoom: 'Zoom zurücksetzen',
      resetZoomTitle: 'Zoom zurücksetzen',
      accessibility: {
        announceNewData: {
          newDataAnnounce: 'Updated data for chart {chartTitle}',
          newPointAnnounceMultiple: 'New data point in chart {chartTitle}: {pointDesc}',
          newPointAnnounceSingle: 'New data point: {pointDesc}',
          newSeriesAnnounceMultiple: 'New data series in chart {chartTitle}: {seriesDesc}',
          newSeriesAnnounceSingle: 'New data series: {seriesDesc}'
        },
        axis: {
          rangeCategories: 'Range: {numCategories} categories.',
          rangeFromTo: 'Range: {rangeFrom} to {rangeTo}.',
          timeRangeDays: 'Range: {range} days.',
          timeRangeHours: 'Range: {range} hours.',
          timeRangeMinutes: 'Range: {range} minutes.',
          timeRangeSeconds: 'Range: {range} seconds.',
          xAxisDescriptionPlural: 'The chart has {numAxes} X axes displaying {#each(names, -1), }and {names[-1]}.',
          xAxisDescriptionSingular: 'The chart has 1 X axis displaying {names[0]}. {ranges[0]}',
          yAxisDescriptionPlural: 'The chart has {numAxes} Y axes displaying {#each(names, -1), }and {names[-1]}.',
          yAxisDescriptionSingular: 'The chart has 1 Y axis displaying {names[0]}. {ranges[0]}'
        },
        chartContainerLabel: '{title}. Highcharts interactive chart.',
        chartTypes: {
          chartTypes: {
            barMultiple: 'Bar chart with {numSeries} data series.',
            barSingle: 'Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.',
            boxplotMultiple: 'Boxplot with {numSeries} data series.',
            boxplotSingle: 'Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.',
            bubbleMultiple: 'Bubble chart with {numSeries} data series.',
            bubbleSingle: 'Bubble chart with {numPoints} {#plural(numPoints, bubbles, bubble)}.',
            columnMultiple: 'Bar chart with {numSeries} data series.',
            columnSingle: 'Bar chart with {numPoints} {#plural(numPoints, bars, bar)}.',
            combinationChart: 'Combination chart with {numSeries} data series.',
            defaultMultiple: 'Chart with {numSeries} data series.',
            defaultSingle: 'Chart with {numPoints} data {#plural(numPoints, points, point)}.',
            emptyChart: 'Empty chart',
            lineMultiple: 'Line chart with {numSeries} lines.',
            lineSingle: 'Line chart with {numPoints} data {#plural(numPoints, points, point)}.',
            mapTypeDescription: 'Map of {mapTitle} with {numSeries} data series.',
            pieMultiple: 'Pie chart with {numSeries} pies.',
            pieSingle: 'Pie chart with {numPoints} {#plural(numPoints, slices, slice)}.',
            scatterMultiple: 'Scatter chart with {numSeries} data series.',
            scatterSingle: 'Scatter chart with {numPoints} {#plural(numPoints, points, point)}.',
            splineMultiple: 'Line chart with {numSeries} lines.',
            splineSingle: 'Line chart with {numPoints} data {#plural(numPoints, points, point)}.',
            unknownMap: 'Map of unspecified region with {numSeries} data series.'
          },
        },
        credits: 'Chart credits: {creditsStr}',
        defaultChartTitle: 'Chart',
        drillUpButton: '{buttonText}',
        exporting: {
          chartMenuLabel: 'Chart menu',
          menuButtonLabel: 'View chart menu, {chartTitle}'
        },
        graphicContainerLabel: '',
        legend: {
          legendLabelNoTitle: 'Toggle series visibility, {chartTitle}',
          legendLabel: 'Chart legend: {legendTitle}',
          legendItem: 'Show {itemName}'
        },
        rangeSelector: {
          dropdownLabel: '{rangeTitle}',
          minInputLabel: 'Select start date.',
          maxInputLabel: 'Select end date.',
          clickButtonAnnouncement: 'Viewing {axisRangeDescription}'
        },
        screenReaderSection: {
          afterRegionLabel: '',
          annotations: {
              descriptionMultiplePoints: '{annotationText}. Related to {annotationPoint}' + '{ Also related to, #each(additionalAnnotationPoints)}',
              descriptionNoPoints: '{annotationText}',
              descriptionSinglePoint: '{annotationText}. Related to {annotationPoint}',
              heading: 'Chart annotations summary'
          },
          beforeRegionLabel: 'Chart screen reader information, {chartTitle}.',
          endOfChartMarker: 'End of interactive chart.'
        },
        series: {
          description: '{description}',
          nullPointValue: 'No value',
          pointAnnotationsDescription: '{Annotation: #each(annotations). }',
          summary: {
            bar: '{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.',
            barCombination: '{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.',
            boxplot: '{name}, boxplot {ix} of {numSeries} with {numPoints} {#plural(numPoints, boxes, box)}.',
            boxplotCombination: '{name}, series {ix} of {numSeries}. Boxplot with {numPoints} {#plural(numPoints, boxes, box)}.',
            bubble: '{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.',
            bubbleCombination: '{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.',
            column: '{name}, bar series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bars, bar)}.',
            columnCombination: '{name}, series {ix} of {numSeries}. Bar series with {numPoints} {#plural(numPoints, bars, bar)}.',
            'default': '{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.',
            defaultCombination: '{name}, series {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.',
            line: '{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.',
            lineCombination: '{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.',
            map: '{name}, map {ix} of {numSeries} with {numPoints} {#plural(numPoints, areas, area)}.',
            mapbubble: '{name}, bubble series {ix} of {numSeries} with {numPoints} {#plural(numPoints, bubbles, bubble)}.',
            mapbubbleCombination: '{name}, series {ix} of {numSeries}. Bubble series with {numPoints} {#plural(numPoints, bubbles, bubble)}.',
            mapCombination: '{name}, series {ix} of {numSeries}. Map with {numPoints} {#plural(numPoints, areas, area)}.',
            mapline: '{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.',
            maplineCombination: '{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.',
            pie: '{name}, pie {ix} of {numSeries} with {numPoints} {#plural(numPoints, slices, slice)}.',
            pieCombination: '{name}, series {ix} of {numSeries}. Pie with {numPoints} {#plural(numPoints, slices, slice)}.',
            scatter: '{name}, scatter plot {ix} of {numSeries} with {numPoints} {#plural(numPoints, points, point)}.',
            scatterCombination: '{name}, series {ix} of {numSeries}, scatter plot with {numPoints} {#plural(numPoints, points, point)}.',
            spline: '{name}, line {ix} of {numSeries} with {numPoints} data {#plural(numPoints, points, point)}.',
            splineCombination: '{name}, series {ix} of {numSeries}. Line with {numPoints} data {#plural(numPoints, points, point)}.'
          },
          xAxisDescription: 'X axis, {name}',
          yAxisDescription: 'Y axis, {name}',
        },
        seriesTypeDescriptions: {
          arearange: 'Arearange charts are line charts displaying a ' + 'range between a lower and higher value for each point.',
          areasplinerange: 'These charts are line charts displaying a ' + 'range between a lower and higher value for each point.',
          boxplot: 'Box plot charts are typically used to display ' + 'groups of statistical data. Each data point in the ' +
                   'chart can have up to 5 values: minimum, lower quartile, ' + 'median, upper quartile, and maximum.',
          bubble: 'Bubble charts are scatter charts where each data ' + 'point also has a size value.',
          columnrange: 'Columnrange charts are column charts ' + 'displaying a range between a lower and higher value for ' + 'each point.',
          errorbar: 'Errorbar series are used to display the ' + 'variability of the data.',
          funnel: 'Funnel charts are used to display reduction of data ' + 'in stages.',
          pyramid: 'Pyramid charts consist of a single pyramid with ' + 'item heights corresponding to each point value.',
          waterfall: 'A waterfall chart is a column chart where each ' + 'column contributes towards a total end value.'
        },
        sonification: {
          playAsSoundButtonText: 'Play as sound, {chartTitle}',
          playAsSoundClickAnnouncement: 'Play'
        },
        svgContainerLabel: 'Interactive chart',
        svgContainerTitle: '',
        table: {
          tableSummary: 'Table representation of chart.',
          viewAsDataTableButtonText: 'View as data table, {chartTitle}'
        },
        zoom: {
          mapZoomIn: 'Zoom chart',
          mapZoomOut: 'Zoom out chart',
          resetZoomButton: 'Reset zoom'
        }
      },
      contextButtonTitle: 'Chart Menü',
      drillUpText: '\u25c1 Back to {series.name}',
      exitFullscreen: 'Exit from full screen',
      exportData: {
        annotationHeader: 'Annotations',
        categoryDatetimeHeader: 'DateTime',
        categoryHeader: 'Category'
      },
      hideData: 'Daten-Tab. ausblenden',
      invalidDate: undefined,
      noData: 'No data to display',
      numericSymbolMagnitude: 1000,
      numericSymbols: ['k', 'M', 'G', 'T', 'P', 'E'],
      printChart: 'Chart drucken',
      shortWeekdays: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
      viewData: 'Daten-Tab. anzeigen',
      viewFullscreen: 'Vollbild',
      stockTools: {
        gui: {
          // Main buttons:
          simpleShapes: 'Einfache Objekte',
          lines: 'Linien',
          crookedLines: 'Crooked lines',
          measure: 'Messungen',
          advanced: 'Advanced',
          toggleAnnotations: 'Annotation ein/aus',
          verticalLabels: 'Vertikale Markierung',
          flags: 'Flags',
          zoomChange: 'Zoomeinstellung ändern',
          typeChange: 'Type change',
          saveChart: 'Save chart',
          indicators: 'Indikatoren',
          currentPriceIndicator: 'Current Price Indikatoren',
          // Other features:
          zoomX: 'Zoom X',
          zoomY: 'Zoom Y',
          zoomXY: 'Zooom XY',
          fullScreen: 'Vollbild',
          typeOHLC: 'OHLC',
          typeLine: 'Linie',
          typeCandlestick: 'Candlestick',
          typeHLC: 'HLC',
          typeHollowCandlestick: 'Hollow Candlestick',
          typeHeikinAshi: 'Heikin Ashi',
          // Basic shapes:
          circle: 'Circle',
          ellipse: 'Ellipse',
          label: 'Text',
          myText: 'Text',
          rectangle: 'Rectangle',
          // Flags:
          flagCirclepin: 'Flag circle',
          flagDiamondpin: 'Flag diamond',
          flagSquarepin: 'Flag square',
          flagSimplepin: 'Flag simple',
          // Measures:
          measureXY: 'Measure XY',
          measureX: 'Measure X',
          measureY: 'Measure Y',
          // Segment, ray and line:
          segment: 'Segment',
          arrowSegment: 'Pfeil Segment',
          ray: 'Ray',
          arrowRay: 'Pfeil Ray',
          line: 'Linie',
          arrowInfinityLine: 'Pfeil Linie',
          horizontalLine: 'Horizontale Linie',
          verticalLine: 'Vertikale Linie',
          infinityLine: 'Infinity Linie',
          // Crooked lines:
          crooked3: 'Crooked 3 line',
          crooked5: 'Crooked 5 line',
          elliott3: 'Elliott 3 line',
          elliott5: 'Elliott 5 line',
          // Counters:
          verticalCounter: 'Vertikaler Zähler',
          verticalLabel: 'Vertikaler Text',
          verticalArrow: 'Vertikaler Pfeil',
          // Advanced:
          fibonacci: 'Fibonacci',
          fibonacciTimeZones: 'Fibonacci Time Zones',
          pitchfork: 'Pitchfork',
          parallelChannel: 'Parallel channel',
          timeCycles: 'Time Cycles'
        }
      },
      navigation: {
        popup: {
          addButton: 'hinzufügen',
          algorithm: 'Algorithm',
          arrowInfinityLine: 'Pfeil Linie',
          arrowRay: 'Pfeil Ray',
          arrowSegment: 'Pfeil Segment',
          average: 'Average',
          background: 'Background',
          backgroundColor: 'Background color',
          backgroundColors: 'Background colors',
          borderColor: 'Border color',
          borderRadius: 'Border radius',
          borderWidth: 'Border width',
          bottomBand: 'Bottom band',
          circle: 'Circle',
          clearFilter: '\u2715 clear filter',
          color: 'Color',
          connector: 'Connector',
          crooked3: 'Crooked 3 line',
          crooked5: 'Crooked 5 line',
          crosshairX: 'Crosshair X',
          crosshairY: 'Crosshair Y',
          decimals: 'Decimals',
          deviation: 'Deviation',
          editButton: 'ändern',
          elliott3: 'Elliott 3 line',
          elliott5: 'Elliott 5 line',
          ellipse: 'Ellipse',
          factor: 'Factor',
          fastAvgPeriod: 'Fast average period',
          fibonacci: 'Fibonacci',
          fibonacciTimeZones: 'Fibonacci Time Zones',
          fill: 'Fill',
          flags: 'Flags',
          fontSize: 'Font size',
          format: 'Text',
          height: 'Height',
          highIndex: 'High index',
          horizontalLine: 'Horizontale Linie',
          increment: 'Increment',
          index: 'Index',
          infinityLine: 'Infinity Line',
          initialAccelerationFactor: 'Initial acceleration factor',
          innerBackground: 'Inner background',
          label: 'Text',
          labelOptions: 'Label options',
          labels: 'Labels',
          line: 'Linie',
          lines: 'Linien',
          longPeriod: 'Long period',
          lowIndex: 'Low index',
          maxAccelerationFactor: 'Max acceleration factor',
          measure: 'Measure',
          measureX: 'Measure X',
          measureXY: 'Measure XY',
          measureY: 'Measure Y',
          multiplier: 'Multiplier',
          multiplierATR: 'ATR multiplier',
          name: 'Name',
          noFilterMatch: 'No match',
          outerBackground: 'Outer background',
          padding: 'Padding',
          parallelChannel: 'Parallel channel',
          period: 'Period',
          periodATR: 'ATR period',
          periods: 'Periods',
          periodSenkouSpanB: 'Senkou Span B period',
          periodTenkan: 'Tenkan period',
          pitchfork: 'Pitchfork',
          ranges: 'Ranges',
          ray: 'Ray',
          rectangle: 'Rectangle',
          removeButton: 'entfernen',
          saveButton: 'speichern',
          searchIndicators: 'Such Indikatoren',
          segment: 'Segment',
          series: 'Series',
          shapeOptions: 'Shape options',
          shapes: 'Shape options',
          shortPeriod: 'Short period',
          signalPeriod: 'Signal period',
          simpleShapes: 'Einfache Objekte',
          slowAvgPeriod: 'Slow average period',
          standardDeviation: 'Standard deviation',
          stroke: 'Line color',
          strokeWidth: 'Line width',
          style: 'Style',
          timeCycles: 'Time Cycles',
          title: 'Title',
          topBand: 'Top band',
          tunnel: 'Tunnel',
          typeOptions: 'Details',
          verticalArrow: 'Vertikaler Pfeil',
          verticalCounter: 'Vertikaler Zähler',
          verticalLabel: 'Vertikaler Text',
          verticalLine: 'Vertikale Linie',
          volume: 'Volume',
          xAxisUnit: 'x-axis unit',
          indicatorAliases: {
            abands: ['Acceleration Bands'],
            bb: ['Bollinger Bands'],
            dema: ['Double Expo. Moving Average'],
            ema: ['Expo. Moving Average'],
            ikh: ['Ichimoku Kinko Hyo'],
            keltnerchannels: ['Keltner Channels'],
            linearRegression: ['Linear Regression'],
            pivotpoints: ['Pivot Points'],
            pc: ['Price Channel'],
            priceenvelopes: ['Price Envelopes'],
            psar: ['Parabolic SAR'],
            sma: ['Simple Moving Average'],
            supertrend: ['Super Trend'],
            tema: ['Triple Expo. Moving Average'],
            vbp: ['Volume by Price'],
            vwap: ['Volume Weighted Moving Average'],
            wma: ['Weighted Moving Average'],
            zigzag: ['Zig Zag'],
            apo: ['Absolute price indicator'],
            ad: ['Accumulation/Distribution'],
            aroon: ['Aroon'],
            aroonoscillator: ['Aroon oscillator'],
            atr: ['Average True Range'],
            ao: ['Awesome oscillator'],
            cci: ['Commodity Channel Index'],
            chaikin: ['Chaikin'],
            cmf: ['Chaikin Money Flow'],
            cmo: ['Chande Momentum Oscillator'],
            disparityindex: ['Disparity Index'],
            dmi: ['Directional Movement Index'],
            dpo: ['Detrended price oscillator'],
            klinger: ['Klinger Oscillator'],
            linearRegressionAngle: ['Linear Regression Angle'],
            linearRegressionIntercept: ['Linear Regression Intercept'],
            linearRegressionSlope: ['Linear Regression Slope'],
            macd: ['Moving Average Convergence Divergence'],
            mfi: ['Money Flow Index'],
            momentum: ['Momentum'],
            natr: ['Normalized Average True Range'],
            obv: ['On-Balance Volume'],
            ppo: ['Percentage Price oscillator'],
            roc: ['Rate of Change'],
            rsi: ['Relative Strength Index'],
            slowstochastic: ['Slow Stochastic'],
            stochastic: ['Stochastic'],
            trix: ['TRIX'],
            williamsr: ['Williams %R']
          }
        }
      }
    }
  }
};