#!/bin/sh

ADDONNAME=ccu-historian
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

stop() {
    echo -n "Stopping CCU-Historian... "
    logger -t homematic -p user.info "stopping ccu-historian"
    start-stop-daemon -K -q -p /var/run/ccu-historian.pid
    echo "OK"
}

start() {
    echo -n "Starting CCU-Historian... "
    logger -t homematic -p user.info "starting ccu-historian"

    if [[ ! -e ${ADDON_DIR}/ccu-historian.config ]]; then
      cp -a ${ADDON_DIR}/ccu-historian-sample.config ${ADDON_DIR}/ccu-historian.config

      # lets set devices.device1.plugin1.type if CUxD is installed
      if [ -x /usr/local/addons/cuxd/cuxd ]; then
        grep -q "devices.device1.plugin1.type=CUXD" ${ADDON_DIR}/ccu-historian.config
        if [ $? -eq 1 ]; then
          echo "devices.device1.plugin1.type=CUXD" >>${ADDON_DIR}/ccu-historian.config
        fi
      fi

      # lets set the own ip address
      ipaddress=$(ip -4 route get 1 | head -1 | cut -d' ' -f8 | tr -d '\n')
      if [ -n "${ipaddress}" ]; then
        sed -i "s/devices\.device1\.address=.*/devices\.device1\.address='${ipaddress}'/g" ${ADDON_DIR}/ccu-historian.config
        sed -i "s/devices\.historianAddress=.*/devices.historianAddress='${ipaddress}'/g" ${ADDON_DIR}/ccu-historian.config
        sed -i "s/webServer\.historianAddress=.*/webServer.historianAddress='${ipaddress}'/g" ${ADDON_DIR}/ccu-historian.config
      fi

      # lets set the data directory
      sed -i '/database\.dir=.*/d' ${ADDON_DIR}/ccu-historian.config
      if [ -d /usr/local/sdcard  ]; then
        # we run on RaspberryMatic
        echo "database.dir='/usr/local/sdcard/ccu-historian/'" >>${ADDON_DIR}/ccu-historian.config
      else
        # we run on CCU2
        echo "database.dir='/media/sd-mmcblk0/ccu-historian/'" >>${ADDON_DIR}/ccu-historian.config
      fi
    fi

    # check which java version and heap size to use.
    if [ -x "/opt/java/bin/java" ]; then
      # we are on RaspberryMatic beta3+
      JAVA_BIN=/opt/java/bin/java
      MAXHEAP=512m
    elif [ -x "/opt/jre/bin/java" ]; then
      # we are on RaspberryMatic beta1-2
      JAVA_BIN=/opt/jre/bin/java
      MAXHEAP=512m
    elif [ -x "/opt/jre-1.8.0_121-compact3/bin/java" ]; then
      # we run on CCU2/YAHM/LXCCU
      JAVA_BIN=/opt/jre-1.8.0_121-compact3/bin/java
      MAXHEAP=192m
    else
      echo "ERROR: Java binary not found"
      logger -t homematic -p user.error "ERROR: Java binary not found for CCU-Historian startup"
    fi

    # lets start ccu-historian
    start-stop-daemon -S -q -b -m -p /var/run/ccu-historian.pid --exec ${JAVA_BIN} -- -Xmx${MAXHEAP} -Djava.util.prefs.userRoot=/usr/local/addons/ccu-historian -Djava.util.prefs.systemRoot=/usr/local/addons/ccu-historian -jar ${ADDON_DIR}/ccu-historian/ccu-historian.jar -config ${ADDON_DIR}/ccu-historian.config -loglevel off
    echo "OK"
}

info() {
    echo "Info: <b>CCU-Historian Add-On</b><br>"
    echo "Info: (c) 2011-2018 Mathias Dzionsko, u.a.<br>"
    echo "Info: <a href="https://github.com/mdzio/ccu-historian" target="_blank">https://github.com/mdzio/ccu-historian</a>"
    echo "Name: CCU-Historian"
    echo "Version: $(cat ${ADDON_DIR}/VERSION)"
    echo "Operations: uninstall restart"
    echo "Config-Url: /addons/ccu-historian/config.cgi"
    echo "Update: /addons/ccu-historian/update-check.cgi"
}

uninstall() {
    stop
    ${ADDON_DIR}/update_addon ccu-historian
    rm -rf ${ADDON_DIR}
    rm ${RCD_DIR}/ccu-historian
    rm -rf ${WWW_DIR}
    logger -t homematic -p user.info "uninstalled ccu-historian"
}

case "$1" in
  ""|start)
	  start
	;;
  stop)
	  stop
	;;
  restart|reload)
	  stop
	  sleep 2
	  start
	;;
  uninstall)
    uninstall
  ;;
  info)
    info
  ;;
  *)
    echo "Usage: ccu-historian {start|stop|restart|info|uninstall}" >&2
    exit 1
  ;;
esac

exit $?
