#!/bin/sh

ADDONNAME=ccu-historian
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

if [ "$1" = "" ]; then
  echo "CCU1"
  lcdtool "Addon not for CCU1...    "
  exit 1
elif [ "$1" = "CCU2" ]; then
  echo "CCU2"
  if [ "`mount | grep ubi1:user | grep /usr/local | wc -l`" -eq 0 ]; then
    mount -t ubifs ubi1:user /usr/local
  fi
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  echo "HM-RASPBERRYMATIC"
  mount /usr/local
fi

# create directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}
mkdir -p ${WWW_DIR}
chmod 755 ${WWW_DIR}

# copy addon
if [ ! -e ${ADDON_DIR}/ccu-historian.config ]; then
  cp -af addon/ccu-historian.config ${ADDON_DIR}/
fi
cp -af ccu-historian ${ADDON_DIR}/
cp -af VERSION ${ADDON_DIR}/

# copy startup script
cp -af addon/rc.d/* ${RCD_DIR}/

# copy www directory
cp -af addon/www/* ${WWW_DIR}/

# add menu entry
touch ${CONFIG_DIR}/hm_addons.cfg
if [ "$1" = "CCU2" ]; then
  cp -af addon/ccu2/update_addon ${ADDON_DIR}/
elif [ "$1" == "HM-RASPBERRYMATIC" ]; then
  cp -af addon/ccurm/update_addon ${ADDON_DIR}/
fi
${ADDON_DIR}/update_addon ccu-historian addon/ccu-historian_addon.cfg

sync

exit 0
