#!/bin/sh

ADDONNAME=ccu-historian
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=/usr/local/etc/config/rc.d
CONFIG_DIR=/usr/local/etc/config
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

# Logging to syslog is currently not supported by the CCU during the install process.

if [ "$1" = "" ]; then
  echo "CCU-Historian Add-On is not for CCU1"
  lcdtool "Add-On is not for CCU1   "
  exit 1
elif [ "$1" = "CCU2" ]; then
  echo "CCU-Historian Add-On is not for CCU2"
  exit 1
# A CCU3 currently masquerades as RaspberryMatic. "CCU3" is currently not defined, but it can happen. 
elif [ "$1" == "HM-RASPBERRYMATIC" -o "$1" == "CCU3" ]; then
  echo "Installing on CCU3/RaspberryMatic"
  mount /usr/local
fi

# stop ccu-historian, if already installed
if [ -f $CONFIG_DIR/rc.d/ccu-historian ]; then
  echo "Previous installation detected"
  $CONFIG_DIR/rc.d/ccu-historian stop
fi

# create directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}
mkdir -p ${WWW_DIR}
chmod 755 ${WWW_DIR}

# copy addon
cp -af addon/ccu-historian-sample.config ${ADDON_DIR}/
cp -af ccu-historian ${ADDON_DIR}/
cp -af VERSION ${ADDON_DIR}/

# copy startup script
cp -af addon/rc.d/* ${RCD_DIR}/

# copy www directory
cp -af addon/www/* ${WWW_DIR}/

# add menu entry
cp -af addon/update_hm_addons.tcl ${ADDON_DIR}/
${ADDON_DIR}/update_hm_addons.tcl -a ccu-historian -name CCU-Historian -url /addons/ccu-historian/config.cgi -de "Betriebsdatenerfassung f&uuml;r die CCU" -en "Operating data acquisition for the CCU"

sync

echo "Installed"

exit 0
